### ISSUE TITLE
Verificação de sintomas

### ISSUE THREAD

**Issue by MatheusRuck** [LFBSilva/N2020#3]
- [x] Fazer uma escala de 0 a 10, nos sintomas febre e falta de ar;

- [x] Se houver falta de ar grave --> inserir na fila para internação

- [x] Se houver febre grave (>38,5) --> inserir na fila para internação

- [x] Calafrio --> se houver mais 2 sintomas inserir na fila para internação

- [x] Tosse seca --> se houver mais 2 sintomas inserir na fila para internação

- [x] Cansaço --> se houver mais 2 sintomas inserir na fila para internação

**Comment by LFBSilva** [comment]
Finalizado
